Acc Tests: Enable all compute tests

diff --git a/script/acceptancetest b/script/acceptancetest
--- a/script/acceptancetest
+++ b/script/acceptancetest
@@ -1,22 +1,48 @@
 #!/bin/bash
 #
-set -e
-set -o pipefail
 set -x
 
 source `dirname $0`/stackenv
 
+timeout="60m"
+failed=
+
 # Run the acceptance tests.
+# Check the error code after each suite, but do not exit early if a suite failed.
 
-# exec go test -p=1 github.com/gophercloud/gophercloud/acceptance/... $@
+# Identity v3
+go test -v -timeout $timeout -tags "fixtures acceptance" ./acceptance/openstack/identity/v3/
+if [[ $? != 0 ]]; then
+  failed=1
+fi
 
-# Only enable these successful test cases
-go test -v -tags "fixtures acceptance" ./acceptance/openstack/identity/v3/
-go test -v -tags "fixtures acceptance" ./acceptance/openstack/networking/v2/
-go test -v -tags "fixtures acceptance" ./acceptance/openstack/blockstorage/v2/
-go test -v -tags "fixtures acceptance" -run "SecGroup|Flavor|Keypair" ./acceptance/openstack/compute/v2/
-go test -v -tags "fixtures acceptance" ./acceptance/openstack/container/v1/
-# To enable more after the fix of https://github.com/gophercloud/gophercloud/issues/818
-# go test -v -tags "fixtures acceptance" ./acceptance/openstack/imageservice/v2/
-# go test -v -tags "fixtures acceptance" ./acceptance/openstack/identity/v2/
-# go test -v -tags "fixtures acceptance" ./acceptance/openstack/compute/v2/
+# Networking v2
+go test -v -timeout $timeout -tags "fixtures acceptance" ./acceptance/openstack/networking/v2/
+if [[ $? != 0 ]]; then
+  failed=1
+fi
+
+# Block Storage v2
+go test -v -timeout $timeout -tags "fixtures acceptance" ./acceptance/openstack/blockstorage/v2/
+if [[ $? != 0 ]]; then
+  failed=1
+fi
+
+# Compute v2
+go test -v -timeout $timeout -tags "fixtures acceptance" ./acceptance/openstack/compute/v2/
+if [[ $? != 0 ]]; then
+  failed=1
+fi
+
+# Container v1
+go test -v -timeout $timeout -tags "fixtures acceptance" ./acceptance/openstack/container/v1/
+if [[ $? != 0 ]]; then
+  failed=1
+fi
+
+# If any of the test suites failed, exit 1
+if [[ -n $failed ]]; then
+  exit 1
+fi
+
+exit 0
